// import '.js'

const lines = [
    "1.8.9",
    "1.20.4",
    "Converting ResourcePack{path=./SammyGreens 1k Subscriber Special}",
    "  Deleting existing conversion",
    "  Copying existing pack",
    "  Running Converters",
    "    Running NameConverter",
    "Finding files that are less than 1.12",
    "Found Items folder, renaming",
    "Found blocks folder, renaming",
    "MCPatcher exists, switching to optifine",
    "      Renamed: sandstone_smooth.png->cut_sandstone.png",
    "      Renamed: double_plant_paeonia_top.png->peony_top.png",
    "      Renamed: hardened_clay_stained_magenta.png->magenta_terracotta.png",
    "      Renamed: glass_pane_top_cyan.png->cyan_stained_glass_pane_top.png",
    "      Renamed: stone_granite_smooth.png->polished_granite.png",
    "      Renamed: deadbush.png->dead_bush.png",
    "      Renamed: mushroom_block_skin_stem.png->mushroom_stem.png",
    "      Renamed: wheat_stage_7.png->wheat_stage7.png",
    "      Renamed: waterlily.png->lily_pad.png",
    "      Renamed: ice_packed.png->packed_ice.png",
    "      Renamed: stonebrick.png->stone_bricks.png",
    "      Renamed: nether_wart_stage_2.png->nether_wart_stage2.png",
    "      Renamed: rail_normal.png->rail.png",
    "      Renamed: anvil_base.png->anvil.png",
    "      Renamed: wool_colored_yellow.png->yellow_wool.png",
    "      Renamed: wheat_stage_3.png->wheat_stage3.png",
    "      Renamed: nether_brick.png->nether_bricks.png",
    "      Renamed: glass_white.png->white_stained_glass.png",
    "      Renamed: glass_black.png->black_stained_glass.png",
    "      Renamed: glass_green.png->green_stained_glass.png",
    "      Renamed: hardened_clay_stained_black.png->black_terracotta.png",
    "      Renamed: rail_activator_powered.png->activator_rail_on.png",
    "      Renamed: glass_pane_top_gray.png->gray_stained_glass_pane_top.png",
    "      Renamed: wool_colored_white.png->white_wool.png",
    "      Renamed: glass_pane_top_white.png->white_stained_glass_pane_top.png",
    "      Renamed: glass_magenta.png->magenta_stained_glass.png",
    "      Renamed: mushroom_block_skin_red.png->red_mushroom_block.png",
    "      Renamed: door_acacia_lower.png->acacia_door_bottom.png",
    "      Renamed: glass_cyan.png->cyan_stained_glass.png",
    "      Renamed: glass_light_blue.png->light_blue_stained_glass.png",
    "      Renamed: wheat_stage_5.png->wheat_stage5.png",
    "      Renamed: log_birch.png->birch_log.png",
    "      Renamed: glass_orange.png->orange_stained_glass.png",
    "      Renamed: dispenser_front_horizontal.png->dispenser_front.png",
    "      Renamed: mushroom_red.png->red_mushroom.png",
    "      Renamed: hardened_clay_stained_gray.png->gray_terracotta.png",
    "      Renamed: hardened_clay_stained_pink.png->pink_terracotta.png",
    "      Renamed: planks_acacia.png->acacia_planks.png",
    "      Renamed: glass_pane_top_yellow.png->yellow_stained_glass_pane_top.png",
    "      Renamed: carrots_stage_3.png->carrots_stage3.png",
    "      Renamed: melon_stem_connected.png->attached_melon_stem.png",
    "      Renamed: double_plant_sunflower_bottom.png->sunflower_bottom.png",
    "      Renamed: stone_andesite_smooth.png->polished_andesite.png",
    "      Renamed: hardened_clay_stained_green.png->green_terracotta.png",
    "      Renamed: mushroom_brown.png->brown_mushroom.png",
    "      Renamed: melon_stem_disconnected.png->melon_stem.png",
    "      Renamed: rail_golden.png->powered_rail.png",
    "      Renamed: double_plant_paeonia_bottom.png->peony_bottom.png",
    "      Renamed: dirt_podzol_side.png->podzol_side.png",
    "      Renamed: stonebrick_cracked.png->cracked_stone_bricks.png",
    "      Renamed: sponge_wet.png->wet_sponge.png",
    "      Renamed: stonebrick_mossy.png->mossy_stone_bricks.png",
    "      Renamed: stone_diorite.png->diorite.png",
    "      Renamed: hardened_clay_stained_blue.png->blue_terracotta.png",
    "      Renamed: glass_pane_top_orange.png->orange_stained_glass_pane_top.png",
    "      Renamed: carrots_stage_1.png->carrots_stage1.png",
    "      Renamed: glass_pane_top_silver.png->light_gray_stained_glass_pane_top.png",
    "      Renamed: redstone_torch_on.png->redstone_torch.png",
    "      Renamed: glass_pane_top_pink.png->pink_stained_glass_pane_top.png",
    "      Renamed: door_jungle_upper.png->jungle_door_top.png",
    "      Renamed: double_plant_rose_top.png->rose_bush_top.png",
    "      Renamed: carrots_stage_2.png->carrots_stage2.png",
    "      Renamed: wool_colored_blue.png->blue_wool.png",
    "      Renamed: grass_side_overlay.png->grass_block_side_overlay.png",
    "      Renamed: hardened_clay_stained_silver.png->light_gray_terracotta.png",
    "      Renamed: double_plant_syringa_top.png->lilac_top.png",
    "      Renamed: door_spruce_upper.png->spruce_door_top.png",
    "      Renamed: wheat_stage_0.png->wheat_stage0.png",
    "      Renamed: potatoes_stage_2.png->potatoes_stage2.png",
    "      Renamed: repeater_off.png->repeater.png",
    "      Renamed: hardened_clay_stained_white.png->white_terracotta.png",
    "      Renamed: log_birch_top.png->birch_log_top.png",
    "      Renamed: wheat_stage_6.png->wheat_stage6.png",
    "      Renamed: door_dark_oak_upper.png->dark_oak_door_top.png",
    "      Renamed: sandstone_normal.png->sandstone.png",
    "      Renamed: stone_diorite_smooth.png->polished_diorite.png",
    "      Renamed: door_acacia_upper.png->acacia_door_top.png",
    "      Renamed: torch_on.png->torch.png",
    "      Renamed: cocoa_stage_1.png->cocoa_stage1.png",
    "      Renamed: hardened_clay.png->terracotta.png",
    "      Renamed: glass_yellow.png->yellow_stained_glass.png",
    "      Renamed: glass_pane_top_blue.png->blue_stained_glass_pane_top.png",
    "      Renamed: glass_purple.png->purple_stained_glass.png",
    "      Renamed: rail_activator.png->activator_rail.png",
    "      Renamed: glass_pane_top_black.png->black_stained_glass_pane_top.png",
    "      Renamed: pumpkin_stem_disconnected.png->pumpkin_stem.png",
    "      Renamed: farmland_wet.png->farmland_moist.png",
    "      Renamed: log_spruce.png->spruce_log.png",
    "      Renamed: flower_rose.png->poppy.png",
    "      Renamed: pumpkin_stem_connected.png->attached_pumpkin_stem.png",
    "      Renamed: noteblock.png->note_block.png",
    "      Renamed: stone_andesite.png->andesite.png",
    "      Renamed: wheat_stage_1.png->wheat_stage1.png",
    "      Renamed: wool_colored_red.png->red_wool.png",
    "      Renamed: anvil_top_damaged_2.png->damaged_anvil_top.png",
    "      Renamed: hardened_clay_stained_cyan.png->cyan_terracotta.png",
    "      Renamed: wool_colored_pink.png->pink_wool.png",
    "      Renamed: sapling_roofed_oak.png->dark_oak_sapling.png",
    "      Renamed: comparator_off.png->comparator.png",
    "      Renamed: fire_layer_0.png->fire_0.png",
    "      Renamed: glass_red.png->red_stained_glass.png",
    "      Renamed: door_iron_lower.png->iron_door_bottom.png",
    "      Renamed: hardened_clay_stained_purple.png->purple_terracotta.png",
    "      Renamed: wool_colored_brown.png->brown_wool.png",
    "      Renamed: wool_colored_magenta.png->magenta_wool.png",
    "      Renamed: glass_silver.png->light_gray_stained_glass.png",
    "      Renamed: pumpkin_face_on.png->jack_o_lantern.png",
    "      Renamed: glass_pane_top_lime.png->lime_stained_glass_pane_top.png",
    "      Renamed: log_acacia_top.png->acacia_log_top.png",
    "      Renamed: flower_oxeye_daisy.png->oxeye_daisy.png",
    "      Renamed: glass_pane_top_magenta.png->magenta_stained_glass_pane_top.png",
    "      Renamed: wool_colored_lime.png->lime_wool.png",
    "      Renamed: trapdoor.png->oak_trapdoor.png",
    "      Renamed: hardened_clay_stained_yellow.png->yellow_terracotta.png",
    "      Renamed: double_plant_sunflower_back.png->sunflower_back.png",
    "      Renamed: web.png->cobweb.png",
    "      Renamed: glass_pane_top_red.png->red_stained_glass_pane_top.png",
    "      Renamed: sandstone_carved.png->chiseled_sandstone.png",
    "      Renamed: carrots_stage_0.png->carrots_stage0.png",
    "      Renamed: glass_pink.png->pink_stained_glass.png",
    "      Renamed: door_wood_upper.png->oak_door_top.png",
    "      Renamed: dropper_front_horizontal.png->dropper_front.png",
    "      Renamed: nether_wart_stage_0.png->nether_wart_stage0.png",
    "      Renamed: log_big_oak.png->dark_oak_log.png",
    "      Renamed: reeds.png->sugar_cane.png",
    "      Renamed: double_plant_sunflower_front.png->sunflower_front.png",
    "      Renamed: trip_wire_source.png->trip_wire_hook.png",
    "      Renamed: pumpkin_face_off.png->carved_pumpkin.png",
    "      Renamed: planks_jungle.png->jungle_planks.png",
    "      Renamed: door_dark_oak_lower.png->dark_oak_door_bottom.png",
    "      Renamed: log_oak_top.png->oak_log_top.png",
    "      Renamed: log_spruce_top.png->spruce_log_top.png",
    "      Renamed: flower_allium.png->allium.png",
    "      Renamed: hardened_clay_stained_red.png->red_terracotta.png",
    "      Renamed: flower_tulip_pink.png->pink_tulip.png",
    "      Renamed: double_plant_sunflower_top.png->sunflower_top.png",
    "      Renamed: potatoes_stage_1.png->potatoes_stage1.png",
    "      Renamed: double_plant_syringa_bottom.png->lilac_bottom.png",
    "      Renamed: door_jungle_lower.png->jungle_door_bottom.png",
    "      Renamed: sapling_oak.png->oak_sapling.png",
    "      Renamed: planks_oak.png->oak_planks.png",
    "      Renamed: wheat_stage_2.png->wheat_stage2.png",
    "      Renamed: glass_pane_top_brown.png->brown_stained_glass_pane_top.png",
    "      Renamed: flower_tulip_white.png->white_tulip.png",
    "      Renamed: fire_layer_1.png->fire_1.png",
    "      Renamed: glass_pane_top_light_blue.png->light_blue_stained_glass_pane_top.png",
    "      Renamed: stonebrick_carved.png->chiseled_stone_bricks.png",
    "      Renamed: log_jungle.png->jungle_log.png",
    "      Renamed: sapling_spruce.png->spruce_sapling.png",
    "      Renamed: planks_spruce.png->spruce_planks.png",
    "      Renamed: sapling_jungle.png->jungle_sapling.png",
    "      Renamed: quartz_ore.png->nether_quartz_ore.png",
    "      Renamed: log_jungle_top.png->jungle_log_top.png",
    "      Renamed: rail_golden_powered.png->powered_rail_on.png",
    "      Renamed: planks_birch.png->birch_planks.png",
    "      Renamed: glass_lime.png->lime_stained_glass.png",
    "      Renamed: grass_side.png->grass_block_side.png",
    "      Renamed: glass_pane_top_purple.png->purple_stained_glass_pane_top.png",
    "      Renamed: hardened_clay_stained_orange.png->orange_terracotta.png",
    "      Renamed: nether_wart_stage_1.png->nether_wart_stage1.png",
    "      Renamed: wool_colored_cyan.png->cyan_wool.png",
    "      Renamed: wheat_stage_4.png->wheat_stage4.png",
    "      Renamed: furnace_front_off.png->furnace_front.png",
    "      Renamed: potatoes_stage_3.png->potatoes_stage3.png",
    "      Renamed: wool_colored_gray.png->gray_wool.png",
    "      Renamed: hardened_clay_stained_light_blue.png->light_blue_terracotta.png",
    "      Renamed: glass_brown.png->brown_stained_glass.png",
    "      Renamed: sapling_acacia.png->acacia_sapling.png",
    "      Renamed: flower_blue_orchid.png->blue_orchid.png",
    "      Renamed: wool_colored_black.png->black_wool.png",
    "      Renamed: log_acacia.png->acacia_log.png",
    "      Renamed: wool_colored_silver.png->light_gray_wool.png",
    "      Renamed: planks_big_oak.png->dark_oak_planks.png",
    "      Renamed: flower_dandelion.png->dandelion.png",
    "      Renamed: wool_colored_orange.png->orange_wool.png",
    "      Renamed: cocoa_stage_2.png->cocoa_stage2.png",
    "      Renamed: glass_pane_top_green.png->green_stained_glass_pane_top.png",
    "      Renamed: anvil_top_damaged_1.png->chipped_anvil_top.png",
    "      Renamed: anvil_top_damaged_0.png->anvil_top.png",
    "      Renamed: rail_detector_powered.png->detector_rail_on.png",
    "      Renamed: sapling_birch.png->birch_sapling.png",
    "      Renamed: cocoa_stage_0.png->cocoa_stage0.png",
    "      Renamed: potatoes_stage_0.png->potatoes_stage0.png",
    "      Renamed: log_oak.png->oak_log.png",
    "      Renamed: double_plant_rose_bottom.png->rose_bush_bottom.png",
    "      Renamed: flower_tulip_red.png->red_tulip.png",
    "      Renamed: wool_colored_green.png->green_wool.png",
    "      Renamed: wool_colored_purple.png->purple_wool.png",
    "      Renamed: door_spruce_lower.png->spruce_door_bottom.png",
    "      Renamed: piston_top_normal.png->piston_top.png",
    "      Renamed: wool_colored_light_blue.png->light_blue_wool.png",
    "      Renamed: log_big_oak_top.png->dark_oak_log_top.png",
    "      Renamed: door_wood_lower.png->oak_door_bottom.png",
    "      Renamed: grass_side_snowed.png->grass_block_snow.png",
    "      Renamed: glass_blue.png->blue_stained_glass.png",
    "      Renamed: tallgrass.png->grass.png",
    "      Renamed: hardened_clay_stained_brown.png->brown_terracotta.png",
    "      Renamed: cobblestone_mossy.png->mossy_cobblestone.png",
    "      Renamed: brick.png->bricks.png",
    "      Renamed: rail_normal_turned.png->rail_corner.png",
    "      Renamed: flower_houstonia.png->azure_bluet.png",
    "      Renamed: door_iron_upper.png->iron_door_top.png",
    "      Renamed: door_birch_lower.png->birch_door_bottom.png",
    "      Renamed: hardened_clay_stained_lime.png->lime_terracotta.png",
    "      Renamed: grass_top.png->grass_block_top.png",
    "      Renamed: door_birch_upper.png->birch_door_top.png",
    "      Renamed: mushroom_block_skin_brown.png->brown_mushroom_block.png",
    "      Renamed: flower_tulip_orange.png->orange_tulip.png",
    "      Renamed: glass_gray.png->gray_stained_glass.png",
    "      Renamed: rail_detector.png->detector_rail.png",
    "      Renamed: stone_granite.png->granite.png",
    "      Renamed: fire_layer_1.png.mcmeta->fire_1.png.mcmeta",
    "      Renamed: fire_layer_0.png.mcmeta->fire_0.png.mcmeta",
    "      Renamed: pumpkin_face_on.png.mcmeta->jack_o_lantern.png.mcmeta",
    "      Renamed: grass.png->grass.png",
    "      Renamed: stone_slab_top.png->smooth_stone.png",
    "      Renamed: stone_slab_side.png->smooth_stone_slab_side.png",
    "      Renamed: dye_powder_blue.png->lapis_lazuli.png",
    "      Renamed: record_mellohi.png->music_disc_mellohi.png",
    "      Renamed: record_strad.png->music_disc_strad.png",
    "      Renamed: book_normal.png->book.png",
    "      Renamed: door_iron.png->iron_door.png",
    "      Renamed: record_13.png->music_disc_13.png",
    "      Renamed: bucket_empty.png->bucket.png",
    "      Renamed: wood_pickaxe.png->wooden_pickaxe.png",
    "      Renamed: slimeball.png->slime_ball.png",
    "      Renamed: rabbit_cooked.png->cooked_rabbit.png",
    "      Renamed: dye_powder_cyan.png->cyan_dye.png",
    "      Renamed: fish_salmon_raw.png->salmon.png",
    "      Renamed: dye_powder_red.png->rose_red.png",
    "      Renamed: gold_pickaxe.png->golden_pickaxe.png",
    "      Renamed: record_wait.png->music_disc_wait.png",
    "      Renamed: porkchop_cooked.png->cooked_porkchop.png",
    "      Renamed: gold_shovel.png->golden_shovel.png",
    "      Renamed: gold_helmet.png->golden_helmet.png",
    "      Renamed: dye_powder_purple.png->purple_dye.png",
    "      Renamed: wood_shovel.png->wooden_shovel.png",
    "      Renamed: minecart_hopper.png->hopper_minecart.png",
    "      Renamed: mutton_cooked.png->cooked_mutton.png",
    "      Renamed: record_chirp.png->music_disc_chirp.png",
    "      Renamed: fish_pufferfish_raw.png->pufferfish.png",
    "      Renamed: carrot_golden.png->golden_carrot.png",
    "      Renamed: spider_eye_fermented.png->fermented_spider_eye.png",
    "      Renamed: wood_hoe.png->wooden_hoe.png",
    "      Renamed: dye_powder_white.png->bone_meal.png",
    "      Renamed: bucket_water.png->water_bucket.png",
    "      Renamed: book_enchanted.png->enchanted_book.png",
    "      Renamed: fireworks.png->firework_rocket.png",
    "      Renamed: gold_leggings.png->golden_leggings.png",
    "      Renamed: record_ward.png->music_disc_ward.png",
    "      Renamed: beef_cooked.png->cooked_beef.png",
    "      Renamed: minecart_normal.png->minecart.png",
    "      Renamed: book_written.png->written_book.png",
    "      Renamed: fish_cod_raw.png->cod.png",
    "      Renamed: minecart_command_block.png->command_block_minecart.png",
    "      Renamed: rabbit_raw.png->rabbit.png",
    "      Renamed: dye_powder_magenta.png->magenta_dye.png",
    "      Renamed: door_acacia.png->acacia_door.png",
    "      Renamed: record_stal.png->music_disc_stal.png",
    "      Renamed: dye_powder_silver.png->light_gray_dye.png",
    "      Renamed: gold_sword.png->golden_sword.png",
    "      Renamed: wooden_armorstand.png->armor_stand.png",
    "      Renamed: potato_baked.png->baked_potato.png",
    "      Renamed: record_mall.png->music_disc_mall.png",
    "      Renamed: potion_bottle_empty.png->potion.png",
    "      Renamed: door_dark_oak.png->dark_oak_door.png",
    "      Renamed: door_wood.png->oak_door.png",
    "      Renamed: potion_bottle_splash.png->splash_potion.png",
    "      Renamed: door_jungle.png->jungle_door.png",
    "      Renamed: potion_bottle_drinkable.png->glass_bottle.png",
    "      Renamed: gold_boots.png->golden_boots.png",
    "      Renamed: record_blocks.png->music_disc_blocks.png",
    "      Renamed: dye_powder_black.png->ink_sac.png",
    "      Renamed: dye_powder_pink.png->pink_dye.png",
    "      Renamed: minecart_chest.png->chest_minecart.png",
    "      Renamed: dye_powder_green.png->cactus_green.png",
    "      Renamed: apple_golden.png->golden_apple.png",
    "      Renamed: fish_cod_cooked.png->cooked_cod.png",
    "      Renamed: mutton_raw.png->mutton.png",
    "      Renamed: dye_powder_brown.png->cocoa_beans.png",
    "      Renamed: potato_poisonous.png->poisonous_potato.png",
    "      Renamed: dye_powder_orange.png->orange_dye.png",
    "      Renamed: gold_axe.png->golden_axe.png",
    "      Renamed: dye_powder_lime.png->lime_dye.png",
    "      Renamed: minecart_furnace.png->furnace_minecart.png",
    "      Renamed: redstone_dust.png->redstone.png",
    "      Renamed: fish_salmon_cooked.png->cooked_salmon.png",
    "      Renamed: bucket_milk.png->milk_bucket.png",
    "      Renamed: map_empty.png->map.png",
    "      Renamed: dye_powder_yellow.png->dandelion_yellow.png",
    "      Renamed: gold_hoe.png->golden_hoe.png",
    "      Renamed: bow_standby.png->bow.png",
    "      Renamed: beef_raw.png->beef.png",
    "      Renamed: seeds_wheat.png->wheat_seeds.png",
    "      Renamed: chicken_raw.png->chicken.png",
    "      Renamed: record_cat.png->music_disc_cat.png",
    "      Renamed: dye_powder_light_blue.png->light_blue_dye.png",
    "      Renamed: wood_sword.png->wooden_sword.png",
    "      Renamed: seeds_melon.png->melon_seeds.png",
    "      Renamed: record_11.png->music_disc_11.png",
    "      Renamed: bucket_lava.png->lava_bucket.png",
    "      Renamed: record_far.png->music_disc_far.png",
    "      Renamed: gold_horse_armor.png->golden_horse_armor.png",
    "      Renamed: fish_clownfish_raw.png->clownfish.png",
    "      Renamed: chicken_cooked.png->cooked_chicken.png",
    "      Renamed: gold_chestplate.png->golden_chestplate.png",
    "      Renamed: door_birch.png->birch_door.png",
    "      Renamed: book_writable.png->writable_book.png",
    "      Renamed: wood_axe.png->wooden_axe.png",
    "      Renamed: porkchop_raw.png->porkchop.png",
    "      Renamed: seeds_pumpkin.png->pumpkin_seeds.png",
    "      Renamed: minecart_tnt.png->tnt_minecart.png",
    "      Renamed: melon_speckled.png->glistering_melon_slice.png",
    "      Renamed: fireball.png->fire_charge.png",
    "      Renamed: door_spruce.png->spruce_door.png",
    "      Renamed: dye_powder_gray.png->gray_dye.png",
    "      Renamed: fishing_rod_uncast.png->fishing_rod.png",
    "      Renamed: cocoa_beans.png->brown_dye.png",
    "      Renamed: dandelion_yellow.png->yellow_dye.png",
    "      Renamed: ink_sac.png->black_dye.png",
    "      Renamed: lapis_lazuli.png->blue_dye.png",
    "      Renamed: cactus_green.png->green_dye.png",
    "      Renamed: rose_red.png->red_dye.png",
    "      Renamed: bone_meal.png->white_dye.png",
    "      Renamed: grass.png->grass.png",
    "      Renamed: grass.png->grass.png",
    "      Renamed: endercrystal_beam.png->end_crystal_beam.png",
    "      Renamed: endercrystal.png->end_crystal.png",
    "    Running PackMetaConverter",
    "    Running CompassConverter",
    "    Running SpacesConverter",
    "    Running ModelConverter",
    "    Running SoundsConverter",
    "    Running AnimationConverter",
    "      Converted lava_still.png.mcmeta",
    "      Converted trip_wire.png.mcmeta",
    "      Converted jack_o_lantern.png.mcmeta",
    "      Converted fire_1.png.mcmeta",
    "      Converted fire_0.png.mcmeta",
    "      Converted water_flow.png.mcmeta",
    "      Converted lava_flow.png.mcmeta",
    "      Converted water_still.png.mcmeta",
    "      Converted clock.png.mcmeta",
    "    Running MapIconConverter",
    "    Running MCPatcherConverter",
    "Updating:sky6.properties",
    "Updating:sky2.properties",
    "Updating:sky4.properties",
    "Updating:sky1.properties",
    "Updating:sky5.properties",
    "Updating:sky8.properties",
    "Updating:sky3.properties",
    "Updating:sky7.properties",
    "    Running WaterConverter",
    "    Running BlockStateConverter",
    "    Running LangConverter",
    "    Running ParticleTextureConverter",
    "    Running ChestConverter",
    "    Running PaintingConverter",
    "    Running MobEffectAtlasConverter",
    "Effect: speed.png",
    "Effect: slowness.png",
    "Effect: haste.png",
    "Effect: mining_fatigue.png",
    "Effect: strength.png",
    "Effect: weakness.png",
    "Effect: poison.png",
    "Effect: regeneration.png",
    "Effect: slow_falling.png",
    "Effect: conduit_power.png",
    "Effect: dolphins_grace.png",
    "Could not find effect with RPID=11",
    "Effect: invisibility.png",
    "Effect: hunger.png",
    "Effect: jump_boost.png",
    "Effect: nausea.png",
    "Effect: night_vision.png",
    "Effect: blindness.png",
    "Effect: resistance.png",
    "Effect: fire_resistance.png",
    "Could not find effect with RPID=264",
    "Could not find effect with RPID=265",
    "Could not find effect with RPID=266",
    "Could not find effect with RPID=267",
    "Effect: water_breathing.png",
    "Effect: wither.png",
    "Effect: absorption.png",
    "Effect: levitation.png",
    "Effect: glowing.png",
    "Effect: luck.png",
    "Effect: unluck.png",
    "Effect: health_boost.png",
    "Could not find effect with RPID=520",
    "Could not find effect with RPID=521",
    "Could not find effect with RPID=522",
    "Could not find effect with RPID=523",
    "    Running EnchantConverter",
    "    Running ParticleConverter",
    "    Running InventoryConverter",
    "    Running AtlasConverter",
    "    Running CreativeTabsConverter",
    "    Running EnchantPathConverter",
    "    Running TitleConverter",
    "    Running SlicerConverter",
]

const sleep = (ms: number) => new Promise((res, _) => setTimeout(res, ms));

async function write_line(console: HTMLPreElement, line: string) {
    console.appendChild(new Text(line + "\n"));
    await sleep(.05 * 1000);

    window.scrollTo(0, 999999);
}

async function main() {
    const cc = document.getElementById("console");
    if (cc == null) {
        console.error("failed to get console");
        return;
    }

    for (const line of lines) {
        await write_line(cc as HTMLPreElement, line);
    }
}

document.addEventListener("DOMContentLoaded", main);